# Generated by Django 4.1.2 on 2022-10-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliderimage",
            name="image",
            field=models.ImageField(upload_to="sliders"),
        ),
    ]
