# Generated by Django 4.1.2 on 2022-10-13 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0003_instagramimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("site_name", models.CharField(max_length=64)),
                ("site_url", models.URLField(max_length=256)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("phone", models.CharField(blank=True, max_length=16, null=True)),
                ("email", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "facebook_link",
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                (
                    "twitter_link",
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                (
                    "instagram_link",
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                (
                    "pinterest_link",
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                ("about_us_text", models.TextField(blank=True, null=True)),
                ("contact_us_text", models.TextField(blank=True, null=True)),
                ("copy_right_text", models.TextField(blank=True, null=True)),
                ("site_logo", models.ImageField(upload_to="site-setting")),
                ("is_main_setting", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("position", models.CharField(max_length=128)),
                ("short_introduction", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="member-images")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(max_length=64)),
                (
                    "site_setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_times_set",
                        to="site_app.sitesetting",
                    ),
                ),
            ],
        ),
    ]
