# Generated by Django 4.1.2 on 2022-10-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0005_alter_businesstime_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="facebook_link",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="linkedin_link",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="twitter_link",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="youtube_link",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
