# Generated by Django 4.1.2 on 2022-10-13 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0006_teammember_facebook_link_teammember_linkedin_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=256)),
                ("subject", models.CharField(max_length=128)),
                ("message", models.TextField()),
            ],
        ),
    ]
