# Generated by Django 4.1.2 on 2022-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0007_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="is_responded",
            field=models.BooleanField(default=False),
        ),
    ]
