# Generated by Django 4.1.2 on 2022-11-17 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("site_app", "0008_contactinfo_is_responded"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountAd",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("text", models.CharField(max_length=128)),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
