# Generated by Django 4.1.2 on 2022-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique order product"
            ),
        ),
    ]
