# Generated by Django 4.1.2 on 2022-10-09 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_unique order product"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCoupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("discount_percentage", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="final_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_set",
                to="orders.ordercoupon",
            ),
        ),
    ]
