# Generated by Django 4.1.2 on 2022-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_ordercoupon_alter_orderitem_final_price_order_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercoupon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
