# Generated by Django 4.1.2 on 2022-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_user_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["is_paid", "-payment_time"]},
        ),
    ]
