# Generated by Django 4.1.2 on 2022-10-05 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("discount_percentage", models.IntegerField(default=0)),
                ("available_quantity", models.IntegerField(default=0)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
