# Generated by Django 4.1.2 on 2022-10-05 12:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=128,
                populate_from=models.CharField(max_length=64),
                unique=True,
            ),
        ),
    ]
