# Generated by Django 4.1.2 on 2022-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productimage_product_productcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "product categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="related_products", to="products.productcategory"
            ),
        ),
    ]
