# Generated by Django 4.1.2 on 2022-10-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productcategory_options_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.productcategory",
            ),
        ),
    ]
