# Generated by Django 4.1.2 on 2022-10-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_product_discounted_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discounted_price",
            field=models.DecimalField(
                decimal_places=2,
                default=models.DecimalField(decimal_places=2, max_digits=6),
                editable=False,
                max_digits=6,
            ),
        ),
    ]
