# Generated by Django 4.1.2 on 2022-10-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0015_alter_product_main_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="related_products_set", to="products.productcategory"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_set",
                to="products.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_set",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvisit",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits_set",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvisit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
