# Generated by Django 4.1.2 on 2022-10-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_alter_productreview_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productreview",
            options={"ordering": ["-create_date"]},
        ),
    ]
